### ISSUE TITLE
Microsoft Computer Vision API key found in source

### ISSUE THREAD

**Issue by johnbindel** [SoojiNoh/analyzePhoto#1]
https://github.com/SoojiNoh/analyzePhoto/blob/43f1cbf338a441e782fe70f75b5fb103ba41e31e/app/src/main/java/com/example/soojinoh/analyzeimage/RecognitionActivity.java

Since the key is checked into public github, _anyone can see/use it_. Consider taking the following steps to remedy this:
1. get a new API key (Azure Portal -> Cognitive Services -> Resource Management (Keys) -> Regenerate)
2. retire usage of key
3. do this with config that is not-version controlled- don't check the new key(s) into GitHub

**Comment by SoojiNoh** [comment]
Thank you so much 
I soon hurried on checking out any unexpected overcharging and figured out there were none fortunately.
I also called MS Azure and asked of any risk of exposing the key, and I was informed that the key was for limited period to be expired.
Thanks again for reminding me the danger 😄 
I should be more careful thu...
